service: tenkarstavern-twitterbot

provider:
  name: aws
  runtime: go1.x
  memorySize: 128
  environment: ${file(./deploy/environments/production.yml)}

package:
 exclude:
   - ./**
 include:
   - ./bin/**

functions:
  tweet:
    handler: bin/tweet
